language: shell
sudo: required
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
  - bats test/*.bats
